package Vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import Controles.PaisControl;
import Controles.CiudadControl;
import Controles.IdiomaControl;
import Conexion.ConexionBD;




public class Vista extends javax.swing.JFrame {

    public Vista() {
        initComponents();
        cargarDatosPais();
        cargarDatosCiudad();
        cargarDatosIdiomas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void cargarDatosPais() {
    // Definir columnas explícitamente
    DefaultTableModel Modelo = new DefaultTableModel(
            new Object[]{"Código", "Nombre", "Continente", "Población", "Tipo Gobierno"}, 0
    );

    // Obtener filtros si los tuvieras (ejemplo: txtNombrePais, etc.)
    String codigo = txtCodigo.getText();
    String nombre = txtNombre.getText();
    String continente = cboxContinente.getSelectedItem() != null 
        ? cboxContinente.getSelectedItem().toString() 
        : "";

    String poblacion = txtPoblacion.getText();
    boolean tipoGobierno = chkTipoGobierno.isSelected();


    // Uso de DAO/Control
    Controles.PaisControl dao = new Controles.PaisControl();
    java.util.List<Modelo.Pais> lista = dao.listarPaises(codigo, nombre, continente, poblacion, tipoGobierno);

    // Llenar el modelo con objetos
    for (Modelo.Pais p : lista) {
        Modelo.addRow(new Object[]{
                p.getCodigoPais(),
                p.getNombrePais(),
                p.getContinentePais(),
                p.getPoblacionPais(),
                p.isTipoGobierno() ? "Democracia" : "Otro"
        });
    }

    // Mensajes de control
    if (lista.isEmpty()) {
        System.out.println("No se encontraron países.");
    } else {
        System.out.println(lista.size() + " países cargados.");
    }

    // Asignar modelo a la tabla
    jTablePais.setModel(Modelo);
}

    
    private void cargarDatosCiudad() {
    DefaultTableModel model = (DefaultTableModel) jTableCiudades.getModel();
    model.setRowCount(0);

    String sql = "SELECT nombreCiudad, poblacionCiudad FROM Ciudad";

    try (Connection conn = Conexion.ConexionBD.conectar();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String nombreCiudad = rs.getString("nombreCiudad");
            
            int poblacion = rs.getInt("poblacionCiudad"); 
            
            Object[] fila = {
                nombreCiudad,
                poblacion,
            };

            model.addRow(fila);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void cargarDatosIdiomas() {
    DefaultTableModel model = (DefaultTableModel) jTableCiudades1.getModel();
    model.setRowCount(0);

    String sql = "SELECT nombreIdioma, oficial FROM idioma";

    try (Connection conn = Conexion.ConexionBD.conectar();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String idioma = rs.getString("nombreIdioma");
            
            int oficialDB = rs.getInt("oficial"); 

            String esOficialTexto = (oficialDB == 1) ? "Sí" : "No";

            Object[] fila = {
                idioma,        
                esOficialTexto
            };

            model.addRow(fila);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar datos de idiomas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPaises = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPoblacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePais = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        chkTipoGobierno = new javax.swing.JCheckBox();
        cboxContinente = new javax.swing.JComboBox<>();
        jPanelCiudades1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCiudades1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnConsultarIdioma = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanelCiudades = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCiudades = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnConsultarCiudad = new javax.swing.JButton();
        jcboxPais = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAISES DEL MUNDO");
        setLocationByPlatform(true);

        jLabel3.setText("Nombre");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel4.setText("Continente");

        jLabel5.setText("Población");

        jTablePais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Continente", "Población", "Tipo de gobierno"
            }
        ));
        jScrollPane1.setViewportView(jTablePais);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("Registro Poblacional Internacional");

        btnCrear.setText("Agregar");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jLabel2.setText("Código");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel16.setText("Tipo de gobierno");

        chkTipoGobierno.setText("Democracia");

        cboxContinente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia", "Europa", "America", "Africa", "Oceania", "Antarctica" }));

        javax.swing.GroupLayout jPanelPaisesLayout = new javax.swing.GroupLayout(jPanelPaises);
        jPanelPaises.setLayout(jPanelPaisesLayout);
        jPanelPaisesLayout.setHorizontalGroup(
            jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaisesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPaisesLayout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(jPanelPaisesLayout.createSequentialGroup()
                            .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel16))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txtPoblacion, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(chkTipoGobierno)
                                .addComponent(cboxContinente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanelPaisesLayout.setVerticalGroup(
            jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaisesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPaisesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboxContinente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(chkTipoGobierno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPaisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnConsultar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Paises", jPanelPaises);

        jTableCiudades1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Idioma", "Oficial"
            }
        ));
        jScrollPane3.setViewportView(jTableCiudades1);

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel11.setText("Registro idioma por pais");

        jLabel12.setText("Pais");

        btnConsultarIdioma.setText("Consultar");
        btnConsultarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarIdiomaActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Brasil", "Chile" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCiudades1Layout = new javax.swing.GroupLayout(jPanelCiudades1);
        jPanelCiudades1.setLayout(jPanelCiudades1Layout);
        jPanelCiudades1Layout.setHorizontalGroup(
            jPanelCiudades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCiudades1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanelCiudades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanelCiudades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnConsultarIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCiudades1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelCiudades1Layout.setVerticalGroup(
            jPanelCiudades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCiudades1Layout.createSequentialGroup()
                .addGroup(jPanelCiudades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCiudades1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCiudades1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanelCiudades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(btnConsultarIdioma)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Idiomas", jPanelCiudades1);

        jTableCiudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ciudad", "Población"
            }
        ));
        jScrollPane2.setViewportView(jTableCiudades);

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel9.setText("Registro ciudades por pais");

        jLabel10.setText("Pais");

        btnConsultarCiudad.setText("Consultar");
        btnConsultarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCiudadActionPerformed(evt);
            }
        });

        jcboxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Brasil", "Chile" }));

        javax.swing.GroupLayout jPanelCiudadesLayout = new javax.swing.GroupLayout(jPanelCiudades);
        jPanelCiudades.setLayout(jPanelCiudadesLayout);
        jPanelCiudadesLayout.setHorizontalGroup(
            jPanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCiudadesLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnConsultarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCiudadesLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcboxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanelCiudadesLayout.setVerticalGroup(
            jPanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCiudadesLayout.createSequentialGroup()
                .addGroup(jPanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCiudadesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCiudadesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanelCiudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jcboxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(btnConsultarCiudad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ciudades", jPanelCiudades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCiudadActionPerformed

    }//GEN-LAST:event_btnConsultarCiudadActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTablePais.getModel();


    int filaSeleccionada = jTablePais.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un país en la tabla para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

  
    String codigo = model.getValueAt(filaSeleccionada, 0).toString();

   
    int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar el país con código " + codigo + "?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    
    try (Connection conn = Conexion.ConexionBD.conectar()) {
        String sql = "DELETE FROM Pais WHERE codigoPais = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, codigo);

        int filasAfectadas = ps.executeUpdate();

        if (filasAfectadas > 0) {
            JOptionPane.showMessageDialog(this, "País eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
       
            model.removeRow(filaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró un país con ese código.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al eliminar en la base de datos: " + ex.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
      String codigoBuscado = txtCodigo.getText().trim();
String continenteSeleccionado = cboxContinente.getSelectedItem().toString();

DefaultTableModel model = (DefaultTableModel) jTablePais.getModel();
model.setRowCount(0);

String sql;
boolean buscarPorCodigo = !codigoBuscado.isEmpty();

if (buscarPorCodigo) {
    sql = "SELECT * FROM Pais WHERE codigoPais = ?";
} else {
    sql = "SELECT * FROM Pais WHERE continentePais = ?";
}

try (Connection conn = Conexion.ConexionBD.conectar();
     PreparedStatement ps = conn.prepareStatement(sql)) {

    if (buscarPorCodigo) {
        ps.setString(1, codigoBuscado);
    } else {
        ps.setString(1, continenteSeleccionado);
    }

    ResultSet rs = ps.executeQuery();

    boolean hayResultados = false;

    while (rs.next()) {
        hayResultados = true;

        String codigo = rs.getString("codigoPais");
        String nombre = rs.getString("nombrePais");
        String continente = rs.getString("continentePais");

        Object poblacionObj = rs.getObject("poblacionPais");
        Integer poblacion = (poblacionObj != null) ? (Integer) poblacionObj : null;

        Object tipoGobiernoObj = rs.getObject("tipoGobierno");
        Boolean tipoGobierno = (tipoGobiernoObj != null) ? (Boolean) tipoGobiernoObj : null;

        Object[] fila = {
            (codigo != null ? codigo : "N/A"),
            (nombre != null ? nombre : "N/A"),
            (continente != null ? continente : "N/A"),
            (poblacion != null ? poblacion : "N/A"),
            (tipoGobierno != null ? (tipoGobierno ? "Democracia" : "Otro") : "N/A")
        };

        model.addRow(fila);
    }

    if (!hayResultados) {
        JOptionPane.showMessageDialog(this,
            "No se encontraron países con ese criterio.",
            "Sin resultados",
            JOptionPane.INFORMATION_MESSAGE);
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this,
        "Error al consultar: " + e.getMessage(),
        "Error",
        JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
try {
    DefaultTableModel model = (DefaultTableModel) jTablePais.getModel();

    String codigo = txtCodigo.getText().trim();
    String nombre = txtNombre.getText().trim();
    String continente = cboxContinente.getSelectedItem().toString();
    int poblacion = Integer.parseInt(txtPoblacion.getText().trim());
    boolean esDemocracia = chkTipoGobierno.isSelected();

    if (codigo.isEmpty() || nombre.isEmpty() || continente.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor completa todos los campos obligatorios.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    Object[] newRow = {codigo, nombre, continente, poblacion, esDemocracia ? "Democracia" : "Otro"};
    model.addRow(newRow);

    try (Connection conn = Conexion.ConexionBD.conectar()) {
        String sql = "INSERT INTO Pais (codigoPais, nombrePais, continentePais, poblacionPais, tipoGobierno) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, codigo);
        ps.setString(2, nombre);
        ps.setString(3, continente);
        ps.setInt(4, poblacion);
        ps.setBoolean(5, esDemocracia);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "País agregado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + ex.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
    }

    txtCodigo.setText("");
    txtNombre.setText("");
    txtPoblacion.setText("");
    cboxContinente.setSelectedIndex(0);
    chkTipoGobierno.setSelected(false);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error: La población debe ser un número válido.", "Dato inválido", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    try {
        DefaultTableModel model = (DefaultTableModel) jTablePais.getModel();

      
        String codigo = txtCodigo.getText().trim(); // clave primaria
        String nombre = txtNombre.getText().trim();
        String continente = cboxContinente.getSelectedItem().toString();
        int poblacion = Integer.parseInt(txtPoblacion.getText().trim());
        boolean esDemocracia = chkTipoGobierno.isSelected();

        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar el código del país a modificar.", "Código requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

      
        try (Connection conn = Conexion.ConexionBD.conectar()) {
            String sql = "UPDATE Pais SET nombrePais = ?, continentePais = ?, poblacionPais = ?, tipoGobierno = ? WHERE codigoPais = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nombre);
            ps.setString(2, continente);
            ps.setInt(3, poblacion);
            ps.setBoolean(4, esDemocracia);
            ps.setString(5, codigo);

            int filasAfectadas = ps.executeUpdate();

            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(this, "País modificado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

           
                int filaSeleccionada = jTablePais.getSelectedRow();
                if (filaSeleccionada != -1) {
                    model.setValueAt(codigo, filaSeleccionada, 0);
                    model.setValueAt(nombre, filaSeleccionada, 1);
                    model.setValueAt(continente, filaSeleccionada, 2);
                    model.setValueAt(poblacion, filaSeleccionada, 3);
                    model.setValueAt(esDemocracia ? "Democracia" : "Otro", filaSeleccionada, 4);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un país con ese código.", "Sin resultados", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar en la base de datos: " + ex.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: La población debe ser un número válido.", "Dato inválido", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnConsultarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarIdiomaActionPerformed

    }//GEN-LAST:event_btnConsultarIdiomaActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarCiudad;
    private javax.swing.JButton btnConsultarIdioma;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboxContinente;
    private javax.swing.JCheckBox chkTipoGobierno;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCiudades;
    private javax.swing.JPanel jPanelCiudades1;
    private javax.swing.JPanel jPanelPaises;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCiudades;
    private javax.swing.JTable jTableCiudades1;
    private javax.swing.JTable jTablePais;
    private javax.swing.JComboBox<String> jcboxPais;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPoblacion;
    // End of variables declaration//GEN-END:variables
}
